sudo tee /opt/monitoring/prometheus/prometheus.yml > /dev/null <<'YAML'
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # We'll enable this later after wiring your Flask app to metrics:
  - job_name: 'flask-app'
    metrics_path: /metrics
    static_configs:
      - targets: ['internship-container:5000']
YAML
